import { z } from 'zod';

export const tortoiseTtsSchema = z.object({
	seed: z.number().default(0),
	text: z
		.string()
		.default(
			'The expressiveness of autoregressive transformers is literally nuts! I absolutely adore them.',
		),
	preset: z.enum(['ultra_fast', 'fast', 'standard', 'high_quality']).default('fast'),
	voice_a: z
		.enum([
			'angie',
			'cond_latent_example',
			'deniro',
			'freeman',
			'halle',
			'lj',
			'myself',
			'pat2',
			'snakes',
			'tom',
			'train_daws',
			'train_dreams',
			'train_grace',
			'train_lescault',
			'weaver',
			'applejack',
			'daniel',
			'emma',
			'geralt',
			'jlaw',
			'mol',
			'pat',
			'rainbow',
			'tim_reynolds',
			'train_atkins',
			'train_dotrice',
			'train_empire',
			'train_kennard',
			'train_mouse',
			'william',
			'random',
			'custom_voice',
			'disabled',
		])
		.default('random'),
	voice_b: z
		.enum([
			'angie',
			'cond_latent_example',
			'deniro',
			'freeman',
			'halle',
			'lj',
			'myself',
			'pat2',
			'snakes',
			'tom',
			'train_daws',
			'train_dreams',
			'train_grace',
			'train_lescault',
			'weaver',
			'applejack',
			'daniel',
			'emma',
			'geralt',
			'jlaw',
			'mol',
			'pat',
			'rainbow',
			'tim_reynolds',
			'train_atkins',
			'train_dotrice',
			'train_empire',
			'train_kennard',
			'train_mouse',
			'william',
			'random',
			'custom_voice',
			'disabled',
		])
		.default('disabled'),
	voice_c: z
		.enum([
			'angie',
			'cond_latent_example',
			'deniro',
			'freeman',
			'halle',
			'lj',
			'myself',
			'pat2',
			'snakes',
			'tom',
			'train_daws',
			'train_dreams',
			'train_grace',
			'train_lescault',
			'weaver',
			'applejack',
			'daniel',
			'emma',
			'geralt',
			'jlaw',
			'mol',
			'pat',
			'rainbow',
			'tim_reynolds',
			'train_atkins',
			'train_dotrice',
			'train_empire',
			'train_kennard',
			'train_mouse',
			'william',
			'random',
			'custom_voice',
			'disabled',
		])
		.default('disabled'),
	cvvp_amount: z.number().min(0).max(1).default(0),
	custom_voice: z.string().optional(),
});

export type TtortoiseTtsInput = z.infer<typeof tortoiseTtsSchema>;
